services:
  api:
    build:
      context: ./RecipesApi
      target: development
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    develop:
      watch:
        - action: rebuild
          path: ./RecipesApi/RecipesApi.csproj
        - action: sync
          path: ./RecipesApi
          target: /src