FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY RecipesApi.csproj .
RUN dotnet restore
COPY . .
# maybe WORKDIR?
RUN dotnet build -c ${BUILD_CONFIGURATION} -o /app/build

FROM build AS publish
RUN dotnet publish -c ${BUILD_CONFIGURATION} -o /app/publish
#maybe /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish app/publish .
ENTRYPOINT [ "dotnet", "RecipesApi.dll" ]